language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "pypy3"
addons:
  apt:
    packages:
    - libenchant-dev
    - aspell-en
cache:
  directories:
  - $HOME/.cache/pip
install:
- pip install pyenchant
script:
- nosetests --verbose

# vim:ts=2 sts=2 sw=2 et
