language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- nightly
- pypy3
addons:
  apt:
    packages:
    - libenchant-dev
    - hunspell-en-us
    - myspell-en-gb
cache:
  directories:
  - $HOME/.cache/pip
install:
- pip install pyenchant
- pip install pyflakes
- pip install docutils
script:
- nosetests --verbose
- ./private/run-pyflakes
- find -name "*.rst" | xargs -L1 -t -I{} rst2xml.py --strict {} /dev/null
- make -C doc

# vim:ts=2 sts=2 sw=2 et
