language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6-dev"
- "3.7-dev"
- pypy3
matrix:
  allow_failures:
  - python: pypy3
addons:
  apt:
    packages:
    - libenchant-dev
    - aspell-en
cache:
  directories:
  - $HOME/.cache/pip
before_install:
- no_pylint=true
- \[ "$TRAVIS_PYTHON_VERSION" = 3.2 ] ||
  [[ "$TRAVIS_PYTHON_VERSION" =~ dev ]] ||
  no_pylint=false
install:
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install --upgrade pip
- pip install pyenchant
- pip install regex
- pip install nose
- pip install pyflakes
- $no_pylint || pip install pylint
- pip install docutils
script:
- ./mwic --version
- python3 -c 'import enchant, pprint; d = enchant.Dict("en-US"); pprint.pprint(vars(d))'
- tests/run-tests --verbose
- private/run-pyflakes
- $no_pylint || private/run-pylint
- make -C doc

# vim:ts=2 sts=2 sw=2 et
